title: 🧪JuanFeDS
email: jmartinezbernal02@gmail.com
description: Notas y reflexiones desde la trinchera de los datos.
twitter_username: JuanFeAngel98
github_username: JuanFeDS
minimal_mistakes_skin: dark
search: true
excerpt_separator: "<!--more-->"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /blog/:title/
# paginate: 7 # amount of posts to show
paginate_path: /page:num/
timezone: America/Bogota

include:
  - _pages
  - _includes

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "JuanFe Martínez B."
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Notas y reflexiones desde la trinchera de los datos."
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/JuanFeAngel98"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/JuanFeDS"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/juanfem98/"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/juanfe-martínez/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/JuanFeAngel98"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/JuanFeDS"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/juanfem98/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
